# Generated by Django 4.2.23 on 2025-06-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='audience',
            field=models.CharField(choices=[('beginners', 'Beginners'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professionals', 'Professionals')], max_length=50),
        ),
        migrations.AlterField(
            model_name='courserequest',
            name='design',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('dark', 'Dark'), ('elegant', 'Elegant'), ('corporate', 'Corporate'), ('creative', 'Creative'), ('minimalist', 'Minimalist'), ('academic', 'Academic'), ('magazine', 'Magazine'), ('tech', 'Tech')], max_length=20),
        ),
    ]
